version: '3.9'

volumes:
  mysql_data: {}

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techchallenge
      MYSQL_USER: rm370154
      MYSQL_PASSWORD: fiap

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: techchallenge:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/techchallenge"
      SPRING_DATASOURCE_USERNAME: rm370154
      SPRING_DATASOURCE_PASSWORD: fiap
    restart: on-failure
