spring.application.name=techchallenge
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/techchallenge?useSSL=false&serverTimezone=America/Sao_Paulo
spring.datasource.username=fiap
spring.datasource.password=fiap
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql
server.port=8080